baseURL = "https://myblog.5588sgfh337755jjg.workers.dev/"
languageCode = "ja"
title = "毎日AI"
buildFuture = true
theme = "PaperMod"
defaultContentLanguage = "ja"

[services]
  [services.googleAnalytics]
    ID = "G-9B9W1RJ5RG"

[params]
  description = "AIツールを毎日使い倒す。活用法・副業・最新情報をわかりやすく発信。"
  author = "Makoto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true

[params.profileMode]
  enabled = true
  title = "毎日AI"
  subtitle = "AIツールを毎日使い倒す。\n活用法・副業・最新情報をわかりやすく発信中。"

  [[params.profileMode.buttons]]
    name = "記事を読む"
    url = "/posts/"

[menu]
  [[menu.main]]
    name = "ホーム"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "記事一覧"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "このブログについて"
    url = "/about/"
    weight = 3
